
import static java.lang.reflect.Array.set;
import javax.swing.JOptionPane;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adristi Iftitah
 */
public class UTS_Restoran extends javax.swing.JFrame {

    private static Object getSelectedItem() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form UTS_restoral
     */
    public UTS_Restoran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbMakanan = new javax.swing.JComboBox<>();
        cbMinum = new javax.swing.JComboBox<>();
        HMakanan = new javax.swing.JTextField();
        HMinuman = new javax.swing.JTextField();
        TT = new javax.swing.JTextField();
        NK = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Pesanan Makanan ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 110, 100, 14);

        jLabel2.setText("Pesanan Minuman");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 150, 100, 14);

        jLabel3.setText("Harga Makanan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 190, 90, 14);

        jLabel4.setText("Harga Minuman ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 230, 90, 14);

        jLabel5.setText("Tanggal Transaksi ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 270, 100, 14);

        jLabel6.setText("Nama Kasir ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 310, 80, 20);

        cbMakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Jenis Makanan-", "Nasi Soto", "Pecel", "Tempe Penyet", "Ayam Goreng", "Bebek Bakar", " " }));
        cbMakanan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMakananActionPerformed(evt);
            }
        });
        getContentPane().add(cbMakanan);
        cbMakanan.setBounds(150, 110, 140, 20);

        cbMinum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Jenis Minuman-", "Es Jeruk", "Jus Apel ", "Jus Semangka", "Soda Gembira", "Es Buah", " " }));
        cbMinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMinumActionPerformed(evt);
            }
        });
        getContentPane().add(cbMinum);
        cbMinum.setBounds(150, 150, 140, 20);
        getContentPane().add(HMakanan);
        HMakanan.setBounds(150, 190, 140, 30);
        getContentPane().add(HMinuman);
        HMinuman.setBounds(150, 230, 140, 30);
        getContentPane().add(TT);
        TT.setBounds(150, 270, 140, 30);
        getContentPane().add(NK);
        NK.setBounds(150, 310, 140, 30);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("EXPOSTRAN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 20, 150, 40);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 370, 70, 30);

        jButton2.setText("Cleaar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 370, 63, 30);

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(210, 370, 63, 30);

        jButton4.setText("Print");
        getContentPane().add(jButton4);
        jButton4.setBounds(310, 370, 55, 30);

        setBounds(0, 0, 448, 544);
    }// </editor-fold>//GEN-END:initComponents

    private void cbMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMakananActionPerformed
        // TODO add your handling code here:

        if(cbMakanan.getSelectedItem().equals("Nasi Soto")){
        HMakanan.setText("Rp. 10000 ");
        }else if(cbMakanan.getSelectedItem().equals("Pecel")){
         HMakanan.setText("Rp. 6000");
        }else if(cbMakanan.getSelectedItem().equals("Tempe Penyet")){
            HMakanan.setText("Rp. 12000");
        }else if(cbMakanan.getSelectedItem().equals("Ayam Goreng")){
            HMakanan.setText("Rp. 9000");
        }else if(cbMakanan.getSelectedItem().equals("Bebek Bakar")){
            HMakanan.setText("Rp. 20000");
                }
    }//GEN-LAST:event_cbMakananActionPerformed

    private void cbMinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMinumActionPerformed
        // TODO add your handling code here:
        if(cbMinum.getSelectedItem().equals("Es Jeruk")){
            HMinuman.setText("Rp. 3000");
        }else
            if (cbMinum.getSelectedItem().equals("Jus Apel")){
            HMinuman.setText("Rp. 5000");
        }else
            if (cbMinum.getSelectedItem().equals("Jus Semangka")){
            HMinuman.setText("Rp. 5000");
        }else
            if (cbMinum.getSelectedItem().equals("Soda Gembira")){
            HMinuman.setText("Rp. 10000");
        }else
            if (cbMinum.getSelectedItem().equals("Es Buah")){
            HMinuman.setText("Rp. 12000");
        }
    }//GEN-LAST:event_cbMinumActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if("".equals(HMakanan.getText())|| "".equals(HMinuman.getText())|| "".equals(TT.getText())||"".equals(NK.getText())){
            JOptionPane.showMessageDialog(this,"Harap Lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);
        }
        int status = 0;
        if(status == 1){
                JOptionPane.showMessageDialog(this,"Data gagal ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                    selectData();
 
            }else{
                JOptionPane.showMessageDialog(this,"Data gagal ditambahkan","Sukses",JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        HMakanan.setText("");
        HMinuman.setText("");
        TT.setText("");
        NK.setText("");
        cbMakanan.getSelectedIndex();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int baris = 0;
        // TODO add your handling code here:

        if (baris != -1){
  
            String SQL = "DELETE FROM t_siswa WHERE jComboBox1='"+cbMakanan+"', jComboBox2='"+cbMinum+"' , HMakanan='"+HMakanan+"' , HMinuman='"+HMinuman+"' ,TT='"+TT+"' , NK='"+NK+"'";
            int status = 0;

            if (status==1){
                JOptionPane.showMessageDialog(this,"Data berhasil dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this,"Data Gagal Dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Pilih Baris Data Terlebih Dahulu","Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UTS_Restoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UTS_Restoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UTS_Restoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UTS_Restoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UTS_Restoran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HMakanan;
    private javax.swing.JTextField HMinuman;
    private javax.swing.JTextField NK;
    private javax.swing.JTextField TT;
    private javax.swing.JComboBox<String> cbMakanan;
    private javax.swing.JComboBox<String> cbMinum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static class set {

        public set() {
        }
    }
}
